[package]
name = "ruke"
version = "0.1.0"
edition = "2021"
authors = ["Kauê Fraga Rodrigues"]
description = "A dead-simple automation tool. Inspired by GNU Make."
license = "MIT"
repository = "https://github.com/kauefraga/ruke"

[dependencies]
