[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/ruke_cli"]

[workspace.package]
authors = ["Kauê Fraga Rodrigues"]
license = "MIT"
repository = "https://github.com/kauefraga/ruke"
