[package]
name = "ruke_core"
version = "0.1.0"
edition = "2021"
description = "The core library of Ruke."
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
